-- MySQL Script generated by MySQL Workbench
-- Wed Jun 28 12:17:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema emmaus_connect_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema emmaus_connect_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emmaus_connect_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `emmaus_connect_db` ;

-- -----------------------------------------------------
-- Table `emmaus_connect_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emmaus_connect_db`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Firstname` VARCHAR(100) NOT NULL,
  `Lastname` VARCHAR(100) NOT NULL,
  `IsAdmmin` TINYINT(1) NOT NULL,
  `Region` VARCHAR(100) NOT NULL,
  `Password` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `emmaus_connect_db`.`model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emmaus_connect_db`.`model` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Brand` VARCHAR(50) NOT NULL,
  `Model_name` VARCHAR(50) NOT NULL,
  `RAM` INT NOT NULL,
  `Memory` INT NOT NULL,
  `Buy_price` INT NULL DEFAULT NULL,
  `Sell_Price` INT NULL DEFAULT NULL,
  `Condition` VARCHAR(50) NOT NULL,
  `Other` VARCHAR(500) NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_model_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_model_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `emmaus_connect_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `emmaus_connect_db`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emmaus_connect_db`.`stock` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model_id` INT NOT NULL,
  PRIMARY KEY (`id`, `model_id`),
  INDEX `fk_stock_model1_idx` (`model_id` ASC) VISIBLE,
  CONSTRAINT `fk_stock_model1`
    FOREIGN KEY (`model_id`)
    REFERENCES `emmaus_connect_db`.`model` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
